name: roboshop

services:
  mongodb:
    build: ./mongodb
    image: mongodb:v1
    container_name: mongodb

  catalogue:
    build: ./catalogue
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb

  frontend:
    build: ./FRONTEND
    image: frontend:v1
    container_name: frontend
    ports:
      - "81:80"
    depends_on:
      - catalogue
      - user
      - cart

  user:
    build: ./user
    image: user:v1
    container_name: user
    depends_on:
      - redis
      - mongodb
    environment:
      MONGO: "true"
      REDIS_URL: "redis://redis:6379"
      MONGO_URL: "mongodb://mongodb:27017/users"

  cart:
    build: ./cart
    image: cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue
    environment:
      REDIS_HOST: "redis"
      CATALOGUE_HOST: "catalogue"
      CATALOGUE_PORT: "8080"

  redis:
    image: redis:7
    container_name: redis

  mysql:
    build: ./mysql
    image: mysql:v1
    container_name: mysql
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: "RoboShop@1"

networks:
  default:
    name: roboshop
    driver: bridge
    external : false