name : roboshop
services:
  mongodb:
    build: ./mongodb
    image: mongodb:v1
    container_name: mongodb

networks:
  default : #All the services in this file can use network
  name: roboshop
  driver : bridge
  